# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import MathApi_pb2 as MathApi__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in MathApi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MathApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/MathApi/Start',
                request_serializer=MathApi__pb2.ArgStart.SerializeToString,
                response_deserializer=MathApi__pb2.RetReply.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/MathApi/Stop',
                request_serializer=MathApi__pb2.ArgModel.SerializeToString,
                response_deserializer=MathApi__pb2.RetReply.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/MathApi/Pause',
                request_serializer=MathApi__pb2.ArgModel.SerializeToString,
                response_deserializer=MathApi__pb2.RetReply.FromString,
                _registered_method=True)
        self.GetModels = channel.unary_unary(
                '/MathApi/GetModels',
                request_serializer=MathApi__pb2.ArgRequest.SerializeToString,
                response_deserializer=MathApi__pb2.Models.FromString,
                _registered_method=True)
        self.GetInputTags = channel.unary_unary(
                '/MathApi/GetInputTags',
                request_serializer=MathApi__pb2.ArgModelName.SerializeToString,
                response_deserializer=MathApi__pb2.Tags.FromString,
                _registered_method=True)
        self.GetOutputTags = channel.unary_unary(
                '/MathApi/GetOutputTags',
                request_serializer=MathApi__pb2.ArgModelName.SerializeToString,
                response_deserializer=MathApi__pb2.Tags.FromString,
                _registered_method=True)
        self.GetConstants = channel.unary_unary(
                '/MathApi/GetConstants',
                request_serializer=MathApi__pb2.ArgModelName.SerializeToString,
                response_deserializer=MathApi__pb2.Constants.FromString,
                _registered_method=True)
        self.Transform = channel.unary_unary(
                '/MathApi/Transform',
                request_serializer=MathApi__pb2.ArgData.SerializeToString,
                response_deserializer=MathApi__pb2.TagsDataArray.FromString,
                _registered_method=True)


class MathApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Функция запуска вычислений
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Функция остановки вычислений
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Функция паузы вычислений
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModels(self, request, context):
        """Функция получения перечня моделей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInputTags(self, request, context):
        """Функция получения перечня входных тегов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOutputTags(self, request, context):
        """Функция получения перечня выходных тегов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConstants(self, request, context):
        """Функция получения перечня констант
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transform(self, request, context):
        """Функция такта вычисления
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MathApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=MathApi__pb2.ArgStart.FromString,
                    response_serializer=MathApi__pb2.RetReply.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=MathApi__pb2.ArgModel.FromString,
                    response_serializer=MathApi__pb2.RetReply.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=MathApi__pb2.ArgModel.FromString,
                    response_serializer=MathApi__pb2.RetReply.SerializeToString,
            ),
            'GetModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModels,
                    request_deserializer=MathApi__pb2.ArgRequest.FromString,
                    response_serializer=MathApi__pb2.Models.SerializeToString,
            ),
            'GetInputTags': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInputTags,
                    request_deserializer=MathApi__pb2.ArgModelName.FromString,
                    response_serializer=MathApi__pb2.Tags.SerializeToString,
            ),
            'GetOutputTags': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOutputTags,
                    request_deserializer=MathApi__pb2.ArgModelName.FromString,
                    response_serializer=MathApi__pb2.Tags.SerializeToString,
            ),
            'GetConstants': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConstants,
                    request_deserializer=MathApi__pb2.ArgModelName.FromString,
                    response_serializer=MathApi__pb2.Constants.SerializeToString,
            ),
            'Transform': grpc.unary_unary_rpc_method_handler(
                    servicer.Transform,
                    request_deserializer=MathApi__pb2.ArgData.FromString,
                    response_serializer=MathApi__pb2.TagsDataArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MathApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MathApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MathApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MathApi/Start',
            MathApi__pb2.ArgStart.SerializeToString,
            MathApi__pb2.RetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MathApi/Stop',
            MathApi__pb2.ArgModel.SerializeToString,
            MathApi__pb2.RetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MathApi/Pause',
            MathApi__pb2.ArgModel.SerializeToString,
            MathApi__pb2.RetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MathApi/GetModels',
            MathApi__pb2.ArgRequest.SerializeToString,
            MathApi__pb2.Models.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInputTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MathApi/GetInputTags',
            MathApi__pb2.ArgModelName.SerializeToString,
            MathApi__pb2.Tags.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOutputTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MathApi/GetOutputTags',
            MathApi__pb2.ArgModelName.SerializeToString,
            MathApi__pb2.Tags.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConstants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MathApi/GetConstants',
            MathApi__pb2.ArgModelName.SerializeToString,
            MathApi__pb2.Constants.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MathApi/Transform',
            MathApi__pb2.ArgData.SerializeToString,
            MathApi__pb2.TagsDataArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
